module LocalizeHelper
  
  @@language = :cz
#  attr_reader :words
  @@words = 
    {
    :Accessory => {:en => "Accessory", :cz => "Příslušenství"},
    :Accommodation_history => {:en => "Accommodation history", :cz => "Historie ubytování"},
    :Accommodation_history_for => {:en => "Accommodation history for", :cz => "Historie ubytování pro"},
    :Accomodation_from => {:en => "Accomodation from", :cz => "Ubytování od"},
    :Accomodation_to => {:en => "Accomodation to", :cz => "Ubytování do"},
    :Account_was_created__log_in => {:en => "Account was created. Log in", :cz => "Úšet byl vytvořen, přihlašte se."},
    :Action => {:en => "Action", :cz => "Akce"},
    :Actual => {:en => "Actual", :cz => ""},
    :Actual_month => {:en => "Actual month", :cz => "Aktuální mesíc"},
    :Actual_rent => {:en => "Actual rent", :cz => "Aktuální nájem"},
    :Actually_accommodated_in_property => {:en => "Actually accommodated in property", :cz => "Aktuálne ubytovaní"},
    :Actually_accommodated_renters => {:en => "Actually accommodated renters", :cz => "Aktuálne ubytovaní nájemníci"},
    :Actor =>  {:en => "Actor", :cz => "Zodpovědný"},
    :Add => {:en => "Add", :cz => "Přidej"},
    :Add_accessory => {:en => "Add accessory", :cz => "Přidej příslušeství"},
    :Add_bill => {:en => "Add bill", :cz => "Zadej platbu"},
    :Add_fitting => {:en => "Add fitting", :cz => "Přidej objekt"},
    :Add_more_data => {:en => "Add more data", :cz => "Přidej další údaje"},
    :Add_penalty => {:en => "Add penalty", :cz => "Přidej penále"},
    :Add_penalty_for_late_pay => {:en => "Add penalty for late pay", :cz => "Přidej penále za pozdní platbu"},
    :Add_room => {:en => "Add room", :cz => "Přidej pokoj"},
    :Add_user => {:en => "Add user", :cz => "Přidej uživatele"},
    :Added_penalty => {:en => "Added penalty", :cz => "Přirazené penále"},
    :Additional_info => {:en => "Additional info", :cz => "Další infromace"},
    :Administrator => {:en => "Administrator", :cz => "Administrator"},
    :Administrator_info => {:en => "Administrator info", :cz => "Iformace o administratorovi"},
    :all => {:en => "All", :cz => "Všechny"},
    :Already_generated_bills => {:en => "Already generated bills", :cz => "Již vygenerované platby"},
    :Amount => {:en => "Amount", :cz => "Částka"},
    :Actor => {:en => "Actor",:cz => "Actor"},
     :Added =>{:en => "Added",:cz => "Přidáno" },
     :Add_note => {:en => "Add note",:cz => "Přidej poznámku" },
     :Add_renter => {:en => "Add renter",:cz => "Přidej nájemníka" },
     :Address =>{:en => "Address",:cz => "Adresa" },
     :April =>{:en => "April",:cz => "Duben" },
     :april =>{:en => "april",:cz => "duben" },                   
     :Are_you_sure => {:en => "Are you sure", :cz => "Jste si jistý"},
     :Area_chargable => {:en => "Area chargable", :cz => "Započitatelná rozloha"},
    :Area_for_TUV => {:en => "Area for TUV", :cz => "Rozloha pro TUV"},
    :Area_for_UT => {:en => "Area for UT", :cz => "Rozloha pro UT "},
    :Area_total => {:en => "Area total", :cz => "Celková rozloha"},
    :Assigned_to => {:en => "Assigned to", :cz => "Přrazeno k"},
     :Area => {:en => "Area",:cz => "Rozloha" }, 
     :August =>{:en => "August",:cz => "Srpen" },
     :august =>{:en => "august",:cz => "srpen" },
     :Autopay_for_rent_succesfully_created => {:en => "Autopay for rent was succesfully created.",                                               :cz => "Pravidelná platba pro nájem byla úspěšně vytvořena."},
    :Autopay_for_actual_rent => {:en => "Autopay for actual rent", :cz => "Automatická platba pro atuálni nájem"},
    :Autopay_for_rent_succesfully_created => {:en => "Autopay for rent succesfully created", :cz => "Automatická platba pro nájem úspešně vytvořena"},
     :Autopay_succesfully_saved => {:en => "Autopay succesfully saved", :cz => ""},
    :Autopays => {:en => "Autopays", :cz => "Automatické platby"},
    :Autopays_associated_with_property => {:en => "Autopays associated with property", :cz => "Automatické platby přirazené nemovitosti"},
    :Base => {:en => "Base", :cz => "Základ"},
    :Base_rent => {:en => "Base rent", :cz => "Základní nájem"},
    :Bathroom => {:en => "Bathroom", :cz => "Koupelna"},
    :Belongs_to => {:en => "Belongs to", :cz => "Patří k"},
    :Bill_management => {:en => "Bill management", :cz => "Správa plateb"},
    :Bill_sum => {:en => "Bill sum", :cz => "Suma plateb"},
    :Bills => {:en => "Bills", :cz => "Platby"},
    :Bills_for_property => {:en => "Bills for property", :cz => "Platby pro nemovitost"},
    :Bills_sum => {:en => "Bills sum", :cz => "Suma plateb"},
    :Bills_total => {:en => "Bills total", :cz => "Platby celkem"},
    :Bills_with_deadline_in_selected_month => {:en => "Bills with deadline in selected month", :cz => "PLatby s deadline v danem měsíci"},
    :Building => {:en => "Building", :cz => "Budova"},
    :By_Deleting_user_will_you_will_loose_all_associated_data_like_bills_and_history_of_accommodation__Continue? => {
      :en => "By deleting user will you will loose all associated data like bills and history of accommodation.  Continue?", 
      :cz => "Smazáním nájemníka stratíte všetky asociované údaje jako platby a historii ubytování. Pokračovat?"},
    :Cadaster => {:en => "Cadaster", :cz => "Katastr"},
    :Cant_close_rent__User_has_unpaid_bills => {:en => "Cant close rent  User has unpaid bills", :cz => "Nelze uzavřít. Uživatel má nezaplacené platby."},
    :Cant_close_rent_while_renter_has_unpaid_bills => {:en => "Cant close rent while renter has unpaid bills", :cz => "Nelze uzavřít. Uživatel má nezaplacené platby."},
    :Cathegory => {:en => "Cathegory", :cz => "Kategorie"},
    :Central => {:en => "Central", :cz => "Centrální"},
    :Central_heating => {:en => "Central heating", :cz => "Centrální topení"},
    :Change_login => {:en => "Change login", :cz => "Zmenit login"},
    :Change_personal_info => {:en => "Change personal info", :cz => "Zmena osobních údajů"},
    :Change_rent => {:en => "Change rent", :cz => "Zmena nájmu"},
    :Char_left => {:en => "Char left", :cz => "Zbýva znaků"},
    :Charge_from => {:en => "Charge from", :cz => "Účtovat od"},
    :Charged_from => {:en => "Charged from", :cz => "Účtovano od"},
    :Chimneys => {:en => "Chimneys", :cz => "Komíny"},
    :Choose_contacs => {:en => "Choose contacs", :cz => "Vyberte kontakty"},
    :City => {:en => "City", :cz => "Město"},
    :Close => {:en => "Close", :cz => "Zavřít"},
    :Close_property => {:en => "Close property", :cz => "Zavřít nemovitost"},
    :Close_rent => {:en => "Close rent", :cz => "Uzavřít nájem"},
    :Closed => {:en => "Closed", :cz => "Zavřeno"},
    :Confirm => {:en => "Confirm", :cz => "Potvrdit"},
    :Contact => {:en => "Contact", :cz => "Kontakt"},
    :Contacts => {:en => "Contacts", :cz => "Kontakty"},
    :Content => {:en => "Content", :cz => "Obsah"},
    :Continue => {:en => "Continue", :cz => "Pokračovat"},
    :Contract_rent_with_componenets => {:en => "Contract rent with componenets", :cz => ""},
     :Complex =>  {:en => "Complex",:cz => "Komplex" },
     :Cost =>     {:en => "Cost",:cz => "Cena" },
     :contracts =>{:en => "Contracts",:cz => "Smlouvy" },
    :Count => {:en => "Count", :cz => ""},
    :Create => {:en => "Create", :cz => "Vytvořit"},
    :Create_autopay_for_rent => {:en => "Create autopay for rent", :cz => "Vytvořit automatiskú platbu pro nájem"},
    :Create_login => {:en => "Create login", :cz => "Vytvořit login"},
    :Create_login_for => {:en => "Create login for", :cz => "Vytvořit login pro"},
    :Create_rent => {:en => "Create rent", :cz => "Vytvořit nájem"},
    :Date => {:en => "Date", :cz => "Datum"},
    :Date_of_birth => {:en => "Date of birth", :cz => "DAtum narození"},
    :Date_of_birth_ID => {:en => "Date of birth ID", :cz => "Datum narození"},
    :Days => {:en => "Days", :cz => "Dni"},
    :Days2 => {:en => "Days2", :cz => "Dnů"},
    :Days_late => {:en => "Days late", :cz => "Pozde dnů"},
    :Days_left => {:en => "Days left", :cz => "Zbýva dnů"},
    :Days_repeat => {:en => "Days repeat", :cz => "Opakovat po dnech"},                   
    :Deadline_date => {:en => "Deadline date", :cz => "Datum splatnosti"},
    :Debit => {:en => "Debit", :cz => "Dluh"},
    :Debtor => {:en => "Debtor", :cz => "Dlužník"},
    :Deadline => {:en => "Deadline",:cz => "Splatnost do" },
    :December=>  {:en => "December",:cz => "Prosinec" },
    :december=>  {:en => "december",:cz => "prosinec" },
    :Delete => {:en => "Delete", :cz => "Smazat"},
    :Delete_also => {:en => "Delete also", :cz => "Smazat taky"},
    :Delete_bill? => {:en => "Delete bill?", :cz => "Smazat platbu?"},
    :Delete_property => {:en => "Delete property", :cz => "Smazat nemovitost"},
    :Detail => {:en => "Detail", :cz => "Detail"},
    :Description => {:en => "Description", :cz => "Popis"},
    :Displaying => {:en => "Displaying", :cz => "Zobrazeno"},
    :Edit_accessory => {:en => "Edit accessory", :cz => "Upravit příslušenství"},
    :Edit_autopay => {:en => "Edit autopay", :cz => "Upravit automatickú platbu"},
    :Edit_bill => {:en => "Edit bill", :cz => "Upravit platbu"},
    :Edit_penalty => {:en => "Edit penalty", :cz => "Upravit penále"},
    :Email => {:en => "Email", :cz => "Email"},
    :End_date => {:en => "End date", :cz => "Den ukončení"},
    :End_pay => {:en => "End pay", :cz => "Poslední platba"},
    :End_rent_on_date => {:en => "End rent on date", :cz => "Ukončit nájem dne"},
    :Ends_on => {:en => "Ends on", :cz => "Končí dne"},
    :Error_changing_password => {:en => "Error changing password", :cz => "Chyba pri zmene hesla"},
    :Error_deleting_item => {:en => "Error deleting item", :cz => "Chyba mazání"},
    :Error_deleting_user => {:en => "Error deleting user", :cz => "Chyba mazání"},
    :Error_moving_renter => {:en => "Error moving renter", :cz => "Chyba stěhování"},
    :Error_occured => {:en => "Error occured", :cz => "Chyba"},
    :Error_reporting_renter => {:en => "Error reporting renter", :cz => "Chyba"},
    :Error_saving_autopay => {:en => "Error saving autopay", :cz => "Chyba"},
    :Error_saving_renter => {:en => "Error saving renter", :cz => "Chyba"},
    :Error_updating_personal_information => {:en => "Error updating personal information", :cz => "Chyba"},
    :Error_updating_rent => {:en => "Error updating rent", :cz => "Chyba"},
    :Evidence_list => {:en => "Evidence list", :cz => "Evidenční list"},
    :Expected => {:en => "Expected", :cz => "Očekávaný"},                    
     :Edit =>     {:en => "Edit",:cz => "Upravit" }, 
     :else =>     {:en => "else",:cz => "jiné" }, 
     :February => {:en => "February",:cz => "Únor" },
     :february => {:en => "february",:cz => "únor" },
     :Fees =>     {:en => "Fees",:cz => "Poplatky" },
     :Fill_information_about_user => {:en => "Fill information about user", :cz => "Zadejte info o uživateli"},
    :Finance => {:en => "Finance", :cz => "Finance"},
     :Finances => {:en => "Finances",:cz => "Finance" },
     :Finances_info => {:en => "Finances info", :cz => "Info o financech"},
    :First_pay => {:en => "First pay", :cz => "První platba"},
    :Fittings => {:en => "Fittings", :cz => "Vybavení"},
     :Flat =>     {:en => "Flat",:cz => "Byt" },
    :Floor => {:en => "Floor", :cz => "Podlaží"},
    :Forward => {:en => "Forward", :cz => "Přeposlat"},
    :found => {:en => "found", :cz => "nalezeno"},
    :From => {:en => "From", :cz => "Od"},
    :Fulfilled => {:en => "Fulfilled", :cz => "Splněno"},
    :Generate_from => {:en => "Generate from", :cz => "Generovat od"},
    :Generation_end => {:en => "Generation end", :cz => "Konec generace"},
    :Graph => {:en => "Graph", :cz => "Graf"},
    :Group => {:en => "Group", :cz => "Skupina"},
    :Heating => {:en => "Heating", :cz => "Topení"},
    :Hide => {:en => "Hide", :cz => "Skrýt"},
    :History_of_accommodated_renters => {:en => "History of accommodated renters", :cz => "Historie ubytovaných nájemníků"},                                 
     :House =>    {:en => "House",:cz => "Dům" },
     :Institution => {:en => "Institution",:cz => "Zařízení" },
    :Inactive => {:en => "Inactive", :cz => ""},
    :Income => {:en => "Income", :cz => "Příjem"},
    :Incoming => {:en => "Incoming", :cz => "Příchozí"},
    :Income_in_month => {:en => "Income in month", :cz => "Příjem v měsíci"},
    :Invalid_autopay_id => {:en => "Invalid autopay id", :cz => "Chyba"},
    :Invalid_email => {:en => "Invalid email", :cz => "Neplatný email"},
    :Item => {:en => "Item", :cz => "Položka"},
    :Item_name2 => {:en => "Item name2", :cz => "Název položky"},
    :Item_succesfully_deleted => {:en => "Item succesfully deleted", :cz => "Smazáno"},
    :Item_succesfully_saved => {:en => "Item succesfully saved", :cz => "Uloženo"},                    
     :Lease =>    {:en => "Lease",:cz => "Pronájem" },                       
     :January =>  {:en => "January",:cz => "Leden" },
     :january =>  {:en => "january",:cz => "leden" },
     :July =>     {:en => "July",:cz => "Červenec" },
     :july =>     {:en => "july",:cz => "červenec" },     
     :June =>     {:en => "June",:cz => "Červen" },
     :june =>     {:en => "june",:cz => "červen" },
    :Last_pay => {:en => "Last pay", :cz => "Poslední platba"},
    :Leave_blank_when_changing_renters_password => {:en => "Leave blank when changing renters password", :cz => "NEchte prázdne pri zmene hesla pro užícatele"},
    :Left_to_pay => {:en => "Left to pay", :cz => "Zbýva doplatit"},
    :Login => {:en => "Login", :cz => "Login"},
    :Login_management => {:en => "Login management", :cz => "Správa účtů"},
    :Logout => {:en => "Logout", :cz => "Odhlásit"},
     :May =>      {:en => "May",:cz => "Květen" },
     :may =>      {:en => "may",:cz => "květen" },
     :March =>    {:en => "March",:cz => "Březen" },
     :march =>    {:en => "march",:cz => "březen" },
     :March => {:en => "March", :cz => ""},
    :May => {:en => "May", :cz => ""},
    :Message => {:en => "Message", :cz => "Správa"},
    :Message_about_new_reported_renter => {:en => "Message about new reported renter", :cz => "Správa o nahlášených nájemnících"},
    :Message_succesfully_sent => {:en => "Message succesfully sent", :cz => "Posláno"},
    :Messages => {:en => "Messages", :cz => "Správy"},
    :Missing_password => {:en => "Missing password", :cz => "Chyba heslo"},
    :Month => {:en => "Month", :cz => "Měsíc"},
    :Month_Year => {:en => "Month Year", :cz => "Měsíc rok"},
    :Months => {:en => "Months", :cz => "Měsíců"},
    :Months2 => {:en => "Months2", :cz => "Měsíců"},
    :Move => {:en => "Move", :cz => "Přestěhovat"},
    :Move_to_new_property => {:en => "Move to new property", :cz => "Přestěhovat do"},
    :My_accommodation => {:en => "My accommodation", :cz => "Moje ubytování"},
    :My_info => {:en => "My info", :cz => "Moje info"},
    :My_messages => {:en => "My messages", :cz => "Moje správy"},
     :Name =>     {:en => "Name",:cz => "Jméno" },
     :Name2 => {:en => "Name", :cz => "Název"},
    :Name_for_users => {:en => "Name for users", :cz => "Jméno pro nájemníka"},
    :Net => {:en => "Net", :cz => "Čistý"},
    :New => {:en => "New", :cz => "Nový"},
    :New_accommodation_in => {:en => "New accommodation in", :cz => "Nové ubatování v"},
    :New_contact => {:en => "New contact", :cz => "Nový kontakt"},
    :New_message => {:en => "New message", :cz => "Nová správa"},
    :New_precept_item => {:en => "New precept item", :cz => ""},
    :New_property_accessory => {:en => "New property accessory", :cz => "Nové příslušenství"},
    :New_rent => {:en => "New rent", :cz => "Nový nájem"},
    :New_reported_renter => {:en => "New reported renter", :cz => "Nový nájemník"},
    :New_value => {:en => "New value", :cz => "Nová hodnota"},
    :No_action => {:en => "No action", :cz => "Žádna akce"},
    :No_autopays_defined => {:en => "No autopays defined", :cz => "Žádne automatické platby definovány"},
    :No_data_selected => {:en => "No data selected", :cz => "Žádne data označeny"},
    :No_defined_autopays_for_property => {:en => "No defined autopays for property", :cz => "Žádne automatické platby definovány"},
    :No_new_messages => {:en => "No new messages", :cz => "Žádne nové správy"},
    :No_reported_renters => {:en => "No reported renters", :cz => "Žádny hlášený uživatelé"},
    :None => {:en => "None", :cz => "Žádne"},
    :Notification => {:en => "Notification", :cz => "Upozornění"},
    :New_property => {:en => "New property",:cz => "Nová nemovitost" },
    :Next =>     {:en => "Next",:cz => "Dále" }, 
    :November=>  {:en => "November",:cz => "Listopad" },
    :november=>  {:en => "november",:cz => "listopad" },
    :None =>     {:en => "None",:cz => "Žádne"},
    :Note =>     {:en => "Note",:cz => "Poznámka"},
    :Notes =>    {:en => "Notes",:cz => "Poznámky" },
    :Number_of_rooms => {:en => "Number of rooms",:cz => "Počet pokojů" },              
    :Obejct_of_pay => {:en => "Object of pay", :cz => "Předmet platby"},
    :Object => {:en => "Object", :cz => "Předmet"},
    :Object_of_pay => {:en => "Object of pay", :cz => "Předmet platby"},
    :Oiginal_message => {:en => "Original message", :cz => "Původní správa"},
    :Old => {:en => "Old", :cz => "Starý"},
    :On_day => {:en => "On day", :cz => "Dne"},
    :Options => {:en => "Options", :cz => "Možnosti"},
    :Order => {:en => "Order", :cz => "Třídit"},
    :Order_by => {:en => "Order by", :cz => "Třídit dle"},
    :Outcome => {:en => "Outcome", :cz => "Výdaj"},
    :Outgoing => {:en => "Outgoing", :cz => "Odchozí"},
    :Own_in_appartement => {:en => "Own in appartement", :cz => "Vlastní v byte"},
    :Owner => {:en => "Owner", :cz => ""},
    :Owner_info => {:en => "Owner info", :cz => ""},
    :October =>  {:en => "October",:cz => "Říjen" },
    :october =>  {:en => "october",:cz => "říjen" },
    :one_room_flat => {:en => "one room flat",:cz => "garsonka" },              
    :September =>  {:en => "September",:cz => "Září" },
    :september =>  {:en => "september",:cz => "září" },
    :Owner => {:en => "Owner", :cz => "Vlastník"},                    
    :Paid => {:en => "Paid", :cz => "Zaplaceno"},
    :Partial_payment => {:en => "Partial payment", :cz => ""},
    :Partially_paid => {:en => "Partially paid", :cz => "Částečne splaceno"},
    :Password => {:en => "Password", :cz => "Heslo"},
    :Password_succesfully_changed => {:en => "Password succesfully changed", :cz => "Heslo změněno"},
    :Pay => {:en => "Pay", :cz => "Zaplatit"},
    :Pay_bills => {:en => "Pay bills", :cz => "Zaplatit platby"},
    :Pay_date => {:en => "Pay date", :cz => "Den platby"},
    :Payments => {:en => "Payments", :cz => "PLatby"},
    :Penalties => {:en => "Penalties", :cz => "Penále"},
    :Penalty => {:en => "Penalty", :cz => "Penále"},
    :Pending_bills => {:en => "Pending bills", :cz => "Čekajíci platby"},
    :Percent => {:en => "Percent", :cz => "Procenta"},
    :Percents_has_to_be_from_interval_0__100 => {:en => "Percents has to be from interval 0  100", :cz => "Procenta musí být z intervalu 1 až 100"},
    :Periodicaly_repeat_every => {:en => "Periodicaly repeat every", :cz => "Opakovat každých"},
    :Person_count => {:en => "Person count", :cz => "Počet osob"},
    :Personal_info => {:en => "Personal info", :cz => "osobní informace"},
    :Personal_informations => {:en => "Personal informations", :cz => "osobní informace"},
    :Picture_succesfully_uploaded => {:en => "Picture succesfully uploaded", :cz => "Obrázek uložen"},
    :Please_fill_username_and_password => {:en => "Please fill username and password", :cz => "Vyplňte login a heslo"},
    :Please_log_in => {:en => "Please log in", :cz => "Prosím přihlašte se"},
    :Postal_code => {:en => "Postal code", :cz => "PSČ"},
    :Price => {:en => "Price", :cz => "Cena"},
    :Price_for_property_accessory => {:en => "Price for property accessory", :cz => "Cena za príslušenství"},
    :Price_with_tax => {:en => "Price with tax", :cz => "Cena s DPH"},
    :Prices_total => {:en => "Prices total", :cz => "Celkem"},
    :Profesion => {:en => "Profesion", :cz => "Profese"},
    :Property_fittings => {:en => "Property fittings", :cz => "Vybavení"},
    :Property_has_been_succesfully_closed => {:en => "Property has been succesfully closed", :cz => "Zavřeno"},
    :Property_info => {:en => "Property info", :cz => "Informace o nemovitosti"},
    :Property_is_closed__Cant_add_renter => {:en => "Property is closed  Cant add renter", :cz => "Menovitost je zavřená. Nelze přidat nájemníka"},
    :Property_was_successfully_created => {:en => "Property was successfully created", :cz => "Vytvořeno"},   
    :property =>   {:en => "property",:cz => "nemovitost"},
    :Property =>   {:en => "Property",:cz => "Nemovitost"},
    :Properties => {:en => "Properties",:cz => "Nemovitosti" },
    :Read => {:en => "Read", :cz => "Přečíst"},
    :Read2 => {:en => "Read2", :cz => "Přečíst"},
    :Real => {:en => "Real", :cz => "Skutečný"},
    :Realized => {:en => "Realized", :cz => "Uskutečněný"},
    :Records_per_page => {:en => "Records per page", :cz => "Záznamu na stranku"},
    :Register_new_user => {:en => "Register new user", :cz => "Registrovat uživatele"},
    :Rent_end_date => {:en => "Rent end date", :cz => "DAtum konce nájmu"},
    :Rent_expiry => {:en => "Rent expiry", :cz => "Konec nájmu"},
    :Rent_from => {:en => "Rent from", :cz => "Nájem od"},
    :Rent_history => {:en => "Rent history", :cz => "Historie nájemného"},
    :Rent_info => {:en => "Rent info", :cz => "Informace o nájmu"},
    :Rent_information => {:en => "Rent information", :cz => "Informace o nájmu"},
    :Rent_percept => {:en => "Rent percept", :cz => "Předpis nájmu"},
    :Rent_precept => {:en => "Rent percept", :cz => "Předpis nájmu"},
    :Rent_succesfully_closed => {:en => "Rent succesfully closed", :cz => "Vytvořen"},
    :Rent_succesfully_updated => {:en => "Rent succesfully updated", :cz => "Upraven"},
    :Rent_to => {:en => "Rent to", :cz => "Nájem do"},
    :Rent_value => {:en => "Rent value", :cz => "Hodnota nájemného"},
    :Renter_has_closed_rent__Cant_change_rent => {:en => "Renter_has closed rent  Cant change rent", :cz => "Nájemník je uzavřený. Nelze měnit nájem"},
    :Renter_has_closed_rent__Cant_move_to_new_property => {:en => "Renter has closed rent  Cant move to new property", :cz => "Nájemník je uzavřený. Nelze stěhovat"},
    :Renter_has_unpaid_bills__Cant_close_rent => {:en => "Renter has unpaid bills  Cant close rent", :cz => "Nájemník má nezaplacené platby. Nelze uzavřit"},
    :Renter_info => {:en => "Renter info", :cz => "Inforamce o nájemníkovi"},
    :Renter_succesfully_moved => {:en => "Renter succesfully moved", :cz => "Přestěhován"},
    :Renter_successfully_reported_and_accommodated => {:en => "Renter successfully reported and accommodated", :cz => "Ohlášen a ubytován"},
    :Renter_was_successfully_created => {:en => "Renter was successfully created", :cz => "Vytvořen"},
    :Renter_was_successfully_updated => {:en => "Renter was successfully updated", :cz => "Upraven"},
    :Renters_actually_accomodated_in_property => {:en => "Renters actually accomodated in property", :cz => "Aktuálne ubytovaní nájemníci"},
    :Renters_count => {:en => "Renters count", :cz => "Počet nájemníku"},
    :Renters_logins => {:en => "Renters logins", :cz => "Loginy nájemníků"},
    :Repeat => {:en => "Repeat", :cz => "Opakovat"},
    :Repeat_payment_every => {:en => "Repeat payment every", :cz => "Opakovat každých"},
    :Reply => {:en => "Reply", :cz => "Odpověď"},
    :Report_event => {:en => "Report event", :cz => ""},
    :Report_person => {:en => "Report person", :cz => "Náhlásit nájemníka"},
    :Report_renter => {:en => "Report renter", :cz => "Náhlásit nájemníka"},
    :Reported_new_renter => {:en => "Reported new renter", :cz => "Nahlášen nový nájemník"},
    :Reported_persons_data => {:en => "Reported persons data", :cz => "Údaje o nahlášenem nájemníkovi"},
    :Reported_renters => {:en => "Reported renters", :cz => "Nahlášení nájemníci"},
    :Reported_since => {:en => "Reported since", :cz => "Nahlášen od"},
    :Room => {:en => "Room", :cz => "Pokoj"},
    :Room_accessories_data => {:en => "Room accessories data", :cz => "Vybavení pokojů"},
    :Room_height => {:en => "Room height", :cz => "Výška pokoje"},
    :Room_name => {:en => "Room name", :cz => "Název pokoje"},
    :Rooms_info => {:en => "Rooms info", :cz => "Informace o pokoji"},              
    :Rent => {:en => "Rent",:cz => "Nájem" },
    :Rent_created => {:en => "Rent was created",:cz => "Nájem byl vytvořen" },
    :Renter => {:en => "Renter", :cz => "Nájemník" },
    :Renters => {:en => "Renters",:cz => "Nájemníci"},
    :Select_autopays_to_stop_generating_them => {:en => "Select autopays to stop generating them", :cz => ""},
    :Select_property => {:en => "Select property", :cz => "Vyberte nemovitost"},
    :Select_room => {:en => "Select room", :cz => "Vyberte pokoj"},
    :Select_type_of_rent => {:en => "Select type of rent", :cz => "Vyberte typ nájmu"},
    :Selected_bills_will_be_deleted => {:en => "Selected bills will be deleted", :cz => "Označené platby budou smazány"},
    :Send => {:en => "Send", :cz => "Pošli"},
    :Send_message => {:en => "Send message", :cz => "Pošli správu"},
    :September => {:en => "September", :cz => "Září"},
    :Service => {:en => "Service", :cz => "SLužba"},
    :Service_data => {:en => "Service data", :cz => "Info o službe"},
    :Service_name2 => {:en => "Service name2", :cz => "Název služby"},
    :Services_data => {:en => "Services data", :cz => "Info o službách"},
    :Show => {:en => "Show", :cz => "Ukaž"},
    :Show_fittings_to_renters => {:en => "Show fittings to renters", :cz => "Zobrazit vybavení nájemníkúm"},
    :Show_payments => {:en => "Show payments", :cz => "Zobrazit plaby"},
    :Show_to_renter => {:en => "Show to renter", :cz => "Zobrazit nájemníkovi"},
    :Simple => {:en => "Simple", :cz => "Jednoduchý"},
    :Space_arrangement => {:en => "Space arrangement", :cz => "Dispozice"},
    :Start_date => {:en => "Start date", :cz => "Záčatek"},
    :Statistic => {:en => "Statistic", :cz => "Statistika"},
    :Statistics => {:en => "Statistics", :cz => "Statistika"},
    :Status => {:en => "Status", :cz => "Stav"},
    :Subject => {:en => "Subject", :cz => "Předmet"},
    :Succesfully_created => {:en => "Succesfully created", :cz => "Vytvořeno"},
    :Surname => {:en => "Surname", :cz => "Příjmení"},               
    :skip => {:en => "skip",:cz => "přeskočit" },              
    :Tarif => {:en => "Tarif", :cz => "Tarif"},
    :Task_and_Reminders => {:en => "Task and Reminders", :cz => "Úkoly a připomínky"},
    :Tasks => {:en => "Tasks", :cz => "Úkoly"},
    :Tax => {:en => "Tax", :cz => "Daň"},
    :Tel => {:en => "Tel", :cz => "Tel"},
    :Telephone => {:en => "Telephone", :cz => "Telefón"},
    :These_bills_were_generted_before_rent_change_Choose_what_to_do => {:en => "These bills were generted before rent change Choose what to do", :cz => "Dříve byly vygenerovány platby. Vyberte co s nima udělat"},
    :Title => {:en => "Title", :cz => "Název"},
    :To => {:en => "To", :cz => "Do"},
    :Todos => {:en => "Todos", :cz => "Úkoly"},
    :Todos_and_reminders => {:en => "Todos and reminders", :cz => "Úkoly a připomínky"},
    :Todos_for_property => {:en => "Todos for property", :cz => "Úkoly pro nemovitost"},
    :Total => {:en => "Total", :cz => "Celkem"},
    :Total_days_spent => {:en => "Total days spent", :cz => "Celkem odbydleno"},
    :Total_month_payment_for_property_use => {:en => "Total month payment for property use", :cz => "Celkem na měsíc za užívaní nemovitosti"},
    :Total_recapitulation => {:en => "Total recapitulation", :cz => "Celkem"},
    :Typ => {:en => "Type", :cz => "Typ"},
    :Task => {:en => "Task",:cz => "Úkol" },
    :Task_manager => {:en => "Task manager",:cz => "Úkolovník" },
    :Type => {:en => "Type", :cz => "Typ" },
    :Unit_user_info => {:en => "Unit user info", :cz => "Informace o uživatelích"},
    :Update => {:en => "Update", :cz => "Upravit"},
    :Update_autopay => {:en => "Update autopay", :cz => "Upravit automatickú platbu"},
    :Update_successfull => {:en => "Update successfull", :cz => "Upraveno"},
    :Update_user => {:en => "Update user", :cz => "Upravit uživatele"},
    :Upload_image => {:en => "Upload image", :cz => "Nahrát obrázek"},
    :User => {:en => "User", :cz => "Užívatel"},
    :User_paid => {:en => "User paid", :cz => "Užívatel zaplatil"},
    :User_succesfully_created => {:en => "User succesfully created", :cz => "Vytvořen"},
    :User_sucesfully_deleted => {:en => "User sucesfully deleted", :cz => "Smazán"},
    :User_update => {:en => "User update", :cz => "Upravit uživatele"},
    :Value => {:en => "Value", :cz => "Hodnota"},
    :Variable_symbol => {:en => "Variable symbol", :cz => "Symbol proměnné"},
    :WC => {:en => "WC", :cz => "WC"},
    :Warm_water => {:en => "Warm water", :cz => "Teplá voda"},
    :Website => {:en => "Website", :cz => "web stránka"},
    :Weeks => {:en => "Weeks", :cz => "Týdny"},
    :Weeks2 => {:en => "Weeks2", :cz => "Týdnů"},
    :Welcome => {:en => "Welcome", :cz => "Vítejte"},
    :When_moving_renters_Unselected_autopays_which_belongs_to_renters_will_be_updated_with_new_property => {:en => "When_moving renters Unselected autopays which belongs to renters will be updated with new property", :cz => "Při stěhování, neoznačené auto platby, které patří nájemníkům budou aktualizováný"},
    :When_you_close_property_you_wont_be_able_to_accomodate_renters_in_it__You_can_open_property_at_any_time => {:en => "When you close property you wont be able to accomodate renters in it  You can open property at any time", :cz => "Po uzavření nemovitosti v ní nebudete moci ubytovat nájemníky. Nemovitost můžete kdykoliv otevřít."},
    :With_percept => {:en => "With percept", :cz => "S předpisem"},
    :Year => {:en => "Year", :cz => "Rok"},
    :You_have => {:en => "You have", :cz => "Máte"},
    :Your_current_login => {:en => "Your current login", :cz => "Aktuálni login"}, 
    :all => {:en => "all", :cz => "Všechny"},
    :base => {:en => "base", :cz => "základ"},
    :closed_rent => {:en => "closed rent", :cz => "zavřený nájem"},
    :count => {:en => "count", :cz => "počet"},
    :create_autopay_rent => {:en => "create autopay rent", :cz => "Vytvořit automatickú platbu na nájem"},
    :delete => {:en => "delete", :cz => "smazat"},
    :edit => {:en => "edit", :cz => "upravit"},
    :expected => {:en => "expected", :cz => "očekávaný"},
    :found => {:en => "found", :cz => "nalezeno"},
    :has_updated_his_personal_information => {:en => "has updated his personal information", :cz => "upravil své osobné údaje"},
    :html => {:en => "html", :cz => "html"},
    :in_total => {:en => "in total", :cz => "celkem"},
    :late => {:en => "late", :cz => "pozdě"},
    :name => {:en => "name", :cz => "jméno"},
    :new => {:en => "new", :cz => "nový"},
    :new_messages => {:en => "new messages", :cz => "nové správy"},
    :new_property => {:en => "new property", :cz => "nová nemovitost"},
    :new_renter => {:en => "new renter", :cz => "nový nájemník"},
    :no_picture_selected => {:en => "no picture selected", :cz => "nevybrán žádny obrázek"},
    :not_a_valid_Jpeg_Gif_or_Png_file => {:en => "not a valid Jpeg Gif or Png file", :cz => "neplatný jpeg gif anebo png súbor"},
    :on => {:en => "on", :cz => "dne"},
    :open => {:en => "open", :cz => "otevřít"},
    :pdf => {:en => "pdf", :cz => "pdf"},
    :pending => {:en => "pending", :cz => "čekajíci"},
    :price_with_tax => {:en => "price with tax", :cz => "cena s DPH"},
    :property_admin => {:en => "property admin", :cz => "správce nemovitosti"},
    :real => {:en => "real", :cz => "skutečný"},
    :renter => {:en => "renter", :cz => "nájemník"},
    :select_property => {:en => "select property", :cz => "vyberte nemovitost"},
    :tarif => {:en => "tarif", :cz => "tarif"},
    :tax => {:en => "tax", :cz => "daň"} 
    }
  
  # Method returns string in selected language.
  # This method if for views
  def get_string(string_name)
    if @@words[string_name]
      return @@words[string_name][@@language]
    else
      return string_name
    end
  end
  
  # Method returns string in selected language.
  # This method if for controllers and models  
  def self.get_string(string_name)
    if @@words[string_name]
      return @@words[string_name][@@language]
    else
      return string_name
    end
  end
   
  
  def self.set_language(lang)
      @@language = lang.to_sym # this makes it into a symbol - like ':en'
  end
end